version: '3.5'

services:
  db:
    container_name: pgd_db
    image: postgres:12.2
    restart: on-failure
    env_file:
      - 'env.env'
    environment:
      PORT: 5432
    # dev only
    ports:
      - 8083:5432
    volumes:
      - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql
      - ./postgres:/var/lib/postgresql/data

volumes:
  postgres:
